databases:
  - name: budget_app
    databaseName: budget_app_ly1q
    user: budget_app_ly1q_user

services:
  - type: web
    name: budget-app-shah
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_ly1q
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false